### ISSUE TITLE
Consider using pre-7.0 definition as the sole H98 one

### ISSUE THREAD

**Issue by treeowl** [ekmett/void#12]
The `newtype` definition of `void` plays badly with optimizations. It's too easy to "optimize" `absurd` into an infinite loop; different versions of GHC are rather sensitive to details that shouldn't really matter, for example. The `data` definition is a straight-up inductive type; I would expect an optimizer to leave the definition of `absurd` alone, blowing up as it should on the first case match.

**Comment by treeowl** [comment]
Bonus: `absurd` can be written without `seq`:

```
absurd (Void x) = absurd x
```

**Comment by ekmett** [comment]
The choice is deliberate as it results in the 'correct' bottom happening. We want the exception they gave us, not a <<loop>>.

`Data.Void` as implemented by GHC is optimized to `data Void`, but doesn't take care to seq the input so if it gets an unsafeCoerced () or whatever, `seq`'ing on it can terminate.

`data Void` with no body isn't as portable as the current definition across older GHC versions, and newer versions of GHC get it from `base` with the definition you want anyways.
