### ISSUE TITLE
Conditionally depend on `semigroups`/`hashable`/`deeepseq`?

### ISSUE THREAD

**Issue by Gabriel439** [ekmett/void#13]
Currently the `semigroups` package description has this `library` clause:

```
library
  default-language: Haskell98
  hs-source-dirs: src
  exposed-modules:
    Data.Void.Unsafe

  if !impl(ghc>=7.9)
    hs-source-dirs: src-old
    exposed-modules: Data.Void

  build-depends:
    base       >= 3   && < 10,
    deepseq    >= 1.1 && < 1.5,
    hashable   >= 1.1,
    semigroups >= 0.8.2
```

... and I was wondering if part of the `build-depends` section should be moved under the conditional expression like this:

```
library
  default-language: Haskell98
  hs-source-dirs: src
  exposed-modules:
    Data.Void.Unsafe

  if !impl(ghc>=7.9)
    hs-source-dirs: src-old
    exposed-modules: Data.Void
    build-depends:
      deepseq    >= 1.1 && < 1.5,
      hashable   >= 1.1,
      semigroups >= 0.8.2

  build-depends:
    base       >= 3   && < 10,
```

My understanding is that the `deepseq`/`hashable`/`semigroups` dependencies are only used by the `Data.Void` module so they should be grouped under the same conditional expression.

The main reason I'm asking about this is is that I would like to be able to unconditionally depend on the `void` package and only pull in the `semigroups`/`hashable`/`deepseq` dependencies for older GHC versions.

**Comment by RyanGlScott** [comment]
#14 should fix this.

**Comment by Gabriel439** [comment]
Thank you!

**Comment by Gabriel439** [comment]
Could you upload this to Hackage?

**Comment by ekmett** [comment]
Shipped.

**Comment by Gabriel439** [comment]
Thank you! :)
