### ISSUE TITLE
Higher kinded Void

### ISSUE THREAD

**Issue by ajnsit** [ekmett/void#9]
I currently have some code for which I require a uninhabitable Functor. I currently just use -

    data VoidF a
    instance Functor VoidF where
      fmap = undefined

Is it possible to have higher kinded versions of Void to use in this situation with appropriate Functor and other instances? Perhaps even `Void1` with kind `* -> *`, `Void2` with kind `* -> * -> *` etc.

**Comment by tomjaguarpaw** [comment]
You could use 'Const Void', 'Const (Const Void)' etc.. (Const is in Control.Applicative)

**Comment by ekmett** [comment]
I think Const Void is the best "official" answer for this for now. It should have all the right instances.

**Comment by ajnsit** [comment]
Yes that's perfect! Thanks! It would be nice to have a blurb about using Const for higher kinded types so it's easier to find.

**Comment by ekmett** [comment]
Since `Void` has moved into base, this package here is more or less just in maintenance mode. I'd take a patch that included a documentation blurb, but I wouldn't expect it to get too well seen out here.
